Fixed scalegen for string type alias
spacemeshos/go-scale pull request #19
Opened 2022-08-16 21:50 UTC by evt

fixed scalegen to work correct for `type Hint string` by applying `string(...)` type conversion in encoder and `Hint(..)` in decoder

2022-08-17 08:09 UTC, fasmat approved these changes

2022-08-17 08:11 UTC, fasmat requested changes
The `string_scale.go` generated file seems to be missing an import to the `nested` package.

2022-08-17 08:31 UTC, evt commented
> The `string_scale.go` generated file seems to be missing an import to the `nested` package.

yup, working on a fix :) cheers

2022-08-17 16:19 UTC, dshulyak approved these changes

2022-08-17 16:19 UTC, dshulyak commented on generate.go
> +	if typ.Kind() == reflect.Array && typ.Elem().Kind() == reflect.Uint8 {
what about array with structs, do we need import for them?)

2022-08-17 21:40 UTC, evt commented on generate.go
> +	if typ.Kind() == reflect.Array && typ.Elem().Kind() == reflect.Uint8 {
looks like it works correct for an array of structs because of a double (or even triple) bug :)
```
func builtin(typ reflect.Type) bool {
	if typ.Kind() == reflect.Ptr {
		return typ.Elem().PkgPath() == ""
	}
	return typ.PkgPath() == ""
}
```
`builtin` returns true for an array while `canonicalPath` returns empty path in this case:
```
func canonicalPath(typ reflect.Type) string {
	if typ.Kind() == reflect.Ptr {
		return typ.Elem().PkgPath()
	}
	return typ.PkgPath()
}
```
we should probably fix both and then add another case to skip to `skipPackageImport`. How do you think @dshulyak ?

2022-08-18 04:34 UTC, dshulyak commented on generate.go
> +	if typ.Kind() == reflect.Array && typ.Elem().Kind() == reflect.Uint8 {
i think the import is skipped if builtin returns true. what needs to be skipped?

2022-08-18 10:53 UTC, evt commented on generate.go
> +	if typ.Kind() == reflect.Array && typ.Elem().Kind() == reflect.Uint8 {
fixed `canonicalPath`, `builtin` and `skipPackageImport` as discussed + added more examples for nested types including array of structs.

2022-08-18 11:52 UTC, merged