Add arm64 runners
spacemeshos/go-scale pull request #76
Opened 2024-01-09 14:41 UTC by fasmat

Closes #62

2024-01-09 15:18 UTC, pigmej requested changes
We need to swithc out of the GH runners for macos.

2024-01-09 15:46 UTC, fasmat commented
switched to self hosted runner instead of GH.

2024-01-10 15:44 UTC, poszu approved these changes

2024-01-10 18:59 UTC, pigmej approved these changes

2024-01-10 18:59 UTC, merged