Added support for uint + fixed encoder for [][]byte
spacemeshos/go-scale pull request #8
Opened 2022-07-31 09:36 UTC by evt

2022-07-31 13:48 UTC, dshulyak requested changes
i thought we discussed uint problem. please change type to uint64 where uint was used, no need to add hacks to cover mistakes

2022-07-31 20:45 UTC, evt commented
@dshulyak yeah, and that would need too many changes in 4 repos. Instead it's much easier to add `uint` support in codec which converts it from/to `uint64` under the hood.

2022-08-01 04:11 UTC, dshulyak commented
it can't be too many changes. just cast uint to uint64 where objects are created

2022-08-01 11:16 UTC, closed without merging

2022-08-01 11:18 UTC, evt commented
@dshulyak closing this one but fix for `[][]byte` encoder is still needed - https://github.com/spacemeshos/go-scale/pull/9 - when you have a mo